# fly.toml app configuration file generated for country-information-service on 2024-03-31T08:26:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'country-information-service'
primary_region = 'jnb'
console_command = '/rails/bin/rails console'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
